### ISSUE TITLE
FEMUG-MGA #3 - DB1

### ISSUE THREAD

**Issue by iamgbayer** [femugmga/palestras#1]
# FEMUG-MGA #3 - DB1
Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

## Detalhes do encontro
[Aqui](http://meetu.ps/33vPSD) você encontra mais detalhes sobre local, horário e outras informações.

## Formato
**Qual seu nome?** 
Guilherme Bayer

**Possui Twitter?, usaremos para divulgar**
guuibayer

**Título da palestra**
Exemplo de título

**Descrição**
Descrição da minha palestra

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1: serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by hiwllc** [comment]
**Qual seu nome?**
Wallace Batista

**Possui Twitter?, usaremos para divulgar**
uselessdevelop

**Título da palestra**
Task Runners

**Descrição**
Um pouco sobre automatizadores de tarefas, e algumas pequenas comparações entre os mais conhecidos, suas soluções e seus problemas e como podemos melhorar nosso workflow com eles.

**Comment by juliovedovatto** [comment]
**Qual seu nome?**
Julio Vedovatto

**Possui Twitter?, usaremos para divulgar**
vdvtt

**Título da palestra**
CSS - não pense tanto em frameworks

**Descrição**
Uma talk leve, com alguns itens explicativos sobre a importância de conhecer mais a fundo do CSS e suas nuances, para não depender tanto de CSS framrworks no dia-a-dia.
