### ISSUE TITLE
FEMUG-MGA #12 - Incubadora Tecnológica de Maringá - UEM

### ISSUE THREAD

**Issue by juliovedovatto** [femugmga/palestras#10]
# FEMUG-MGA 12 - Incubadora Tecnológica de Maringá - UEM

Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

## Detalhes do encontro
[Aqui](https://goo.gl/5kr6sm) você encontra mais detalhes sobre local, horário e inscrição.

## Formato
**Qual seu nome?** 
Julio Vedovatto

**Possui Twitter?, usaremos para divulgar**
vdvtt

**Título da palestra**
Exemplo de título

**Descrição**
Descrição da minha palestra

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1: serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by dotenorio** [comment]
**Qual seu nome?**
Fernando M Tenório

**Possui Twitter?, usaremos para divulgar**
dotenorio

**Título da palestra**
AMP - Accelerated mobile pages

**Descrição**
Você sabe o que é AMP? Na realidade eu também não sei mais vota em mim que eu te conto.

**Comment by leonardoelias** [comment]
**Qual seu nome?**
Leonardo Elias

**Possui Twitter?, usaremos para divulgar**
@leonardoelias_

**Título da palestra**
Perceived Performance ou como fazer sua aplicação se sentir mais rápida

**Descrição**
Performance é UX. Quem te fala se seu site está rápido ou não é o usuário. Velocidade depende mais da percepção do usuário que do número medido no cronômetro.

**Comment by juliovedovatto** [comment]
Obrigado a todos pelas propostas. Mais detalhes do evento podem ser acompanhador por aqui
