### ISSUE TITLE
# FEMUG-MGA 13 - ORBITAL Aceleradora 

### ISSUE THREAD

**Issue by iamgbayer** [femugmga/palestras#11]
# FEMUG-MGA 13 - ORBITAL Aceleradora

Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

## Detalhes do encontro
[Aqui](https://goo.gl/2RHUi3) você encontra mais detalhes sobre local, horário e inscrição.

## Formato
**Qual seu nome?** 
Guilherme Bayer

**Possui Twitter?, usaremos para divulgar**
guuibayer

**Título da palestra**
Exemplo de título

**Descrição**
Descrição da minha palestra

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1: serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by uselessdev** [comment]
**Qual seu nome?**
Wallace Batista

**Possui Twitter?, usaremos para divulgar**
uselessdevelop

**Título da palestra**
DFA e gerenciamento de estado

**Descrição**
Nem sempre é simples gerenciar estado de uma aplicação, se ela cresce demais vários cenários não previstos podem aparecer durante o desenvolvimento e é aqui que venho falar de um modelo que pode simplificar esse processo vamos falar um pouco DFA e como isso pode ser aplicado ao gerenciamento de estados de uma aplicação.

**Comment by wwwflorencio** [comment]
**Qual seu nome?**
Marcos Florencio

**Possui Twitter?, usaremos para divulgar**
eptaccio

**Título da palestra**
Javascript e boas práticas

**Descrição**
Hacks, métodos, formas de organizar o código e boas práticas em prol de melhor leitura do código, manutenção futura em projetos javascript.
