### ISSUE TITLE
FEMUG-MGA 14 - UDS Tecnologia

### ISSUE THREAD

**Issue by juliovedovatto** [femugmga/palestras#12]
# FEMUG-MGA 14 - UDS Tecnologia

Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

## Detalhes do encontro
[Aqui](https://goo.gl/QqRx3i) você encontra mais detalhes sobre local, horário e inscrição.

## Formato
**Qual seu nome?** 
Julio Vedovatto

**Possui Twitter?, usaremos para divulgar**
@vdvtt

**Título da palestra**
Exemplo de título

**Descrição**
Descrição da minha palestra

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1: serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by iamgbayer** [comment]
**Qual seu nome?** 
Guilherme Bayer

**Possui Twitter?, usaremos para divulgar**
@guuibayer

**Título da palestra**
Typescript?

**Descrição**
Irei comentar sobre suas funcionalidades, a experiência que estou tendo a um tempo utilizando a ferramenta, seus beneficios e contras.

**Comment by tonydzn** [comment]
Qual seu nome?
Tony Ananias

Possui Twitter?, usaremos para divulgar
@tonyananias

Título da palestra
SEO

Descrição
Imformações essenciais sobre SEO offpage e onpage.
