### ISSUE TITLE
FEMUG-MGA 15 - Objective Solutions

### ISSUE THREAD

**Issue by iamgbayer** [femugmga/palestras#13]
# FEMUG-MGA 15 - Objective Solutions

Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

## Detalhes do encontro
[Aqui](https://goo.gl/iimSMV) você encontra mais detalhes sobre local, horário e inscrição.

## Formato
**Qual seu nome?** 
Julio Vedovatto

**Possui Twitter?, usaremos para divulgar**
@vdvtt

**Título da palestra**
Exemplo de título

**Descrição**
Descrição da minha palestra

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1: serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by luisberns** [comment]
**Qual seu nome?**
Luís Berns

**Possui Twitter?**
@louisuntitled

**Título da palestra**
Hipóteses e não premissas! Como a cultura da empresa impacta no UX do produto.

**Descrição**
Trabalhar assumindo hipóteses e não premissas ou certezas sobre os usuários, gera grande influência na forma que os times interagem e abrem portas para erros rápidos e aprendizados constantes. 

Vou apresentar algumas abordagens com o viés de design utilizando hipóteses, como a cultura pode impactar nesse processo e como podemos gerar mudanças nas organizações através do design.

**Comment by gustavoquinalha** [comment]
**Qual seu nome?**
Gustavo Quinalha

**Possui Twitter?**
@gustavoquinalha

**Título da palestra**
Lidando com microinterações

**Descrição**
O que é, porque usar, como usar, demos e dicas.

**Comment by beliganteop** [comment]
**Qual seu nome?**
Gustavo Beligante

**Possui Github?**
https://github.com/beligante

**Título da palestra**
Performance do front-end depois do HTTP/2

**Descrição**
O HTTP 1.1 fez seu 20º aniversário em 2017 e tornou-se fundamental para o desenvolvimento da Web ao longo dessas duas décadas. Em 2015, a versão 2.0 do protocolo foi lançada com novos recursos impressionantes! 

A nova versão do protocolo vem com a promessa de tornar nossos aplicativos mais rápidos, mais simples e mais robustos - uma combinação rara - nos permitindo desfazer muitas das soluções alternativas HTTP / 1.1 feitas anteriormente em nossos aplicativos e abordar essas preocupações dentro da própria camada de transporte. Ainda melhor, também abre uma série de novas oportunidades para otimizar nossas aplicações e melhorar o desempenho!

**Comment by juliovedovatto** [comment]
Call for Papers encerrado. Agradecemos a participação e votos nos temas propostos. Para mais detalhes, acompanhem o evento.
