### ISSUE TITLE
FEMUG-MGA 16 - Universidade Estadual de Maringá

### ISSUE THREAD

**Issue by juliovedovatto** [femugmga/palestras#14]
FEMUG-MGA 16 - UEM
Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

Detalhes do encontro
Aqui você encontra mais detalhes sobre local, horário e inscrição.

Formato
Qual seu nome?
Julio Vedovatto

Possui Twitter?, usaremos para divulgar
@vdvtt

Título da palestra
Exemplo de título

Descrição
Descrição da minha palestra

Votação
Para tornar a votação democrática as palestras aqui submetidas com mais 👍 serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by dotenorio** [comment]
**Qual seu nome?**
Fernando M Tenório

**Possui Twitter?, usaremos para divulgar**
https://dotenorio.com/twitter

**Título da palestra**
Hexo, só mais um projeto javascript para agilizar as coisas

**Descrição**
Bom, nessa talk pretendo mostrar como o Hexo funciona, do que ele é feito e outras coisinhas a mais.
Quem sabe você use ele no futuro 😄

**Comment by juniorconte** [comment]
**Qual seu nome?**
Junior Conte

**Possui Twitter?, usaremos para divulgar**
https://twitter.com/juniorconte

**Título da palestra**
50 tons de Front-end

**Descrição**
Vamos falar sobre masoquismo, sofrimento e dor, em uma conversa não monocromática sobre carreira e mercado, sob a perspectiva de quem já esteve dos dois lados do balcão. Afinal, o que é um Front-end Designer, UX, Front-end Engineer, Front-end Developer?

Nesta talk, irei compartilhar as descobertas de 6 anos de carreira como profissional do Front, com a apresentação de um compilado de entrevistas feitas com outros profissionais, além de algumas analogias que me ajudaram a sair desta "crise existencial" em busca de saber o tipo de profissional que sou.

**Comment by andrevandal** [comment]
**Qual seu nome?**
André Van Dal

**Possui Twitter?, usaremos para divulgar**
@derevandal

**Título da palestra**
SEO & SMO para desenvolvedores

**Descrição**
O ramo de atuação de um especialista em marketing digital é muito amplo. Mesmo assim, há certas coisas que podem ser feito no âmbito do desenvolvimento que podem facilitar e muito o desempenho do sites em buscadores e redes sociais.

Iniciarei o papo demonstrando o conceito da web 3.0, através de uma análise histórica, e, depois, vamos até alguns exemplos práticos de semântica, acessibilidade, meta dados, micro dados, performance e algumas ferramentas para análise. O intuito é dar uma visão para os desenvolvedores sobre o assunto e tornar mais fácil a integração entre o pessoal do marketing com o pessoal do desenvolvimento.

**Comment by juliovedovatto** [comment]
Call for Papers encerrado. Agradecemos a participação e votos nos temas propostos. Para mais detalhes, acompanhem o evento.
