### ISSUE TITLE
FEMUG-MGA 17 - UniCesumar

### ISSUE THREAD

**Issue by juliovedovatto** [femugmga/palestras#15]
FEMUG-MGA 17 - UniCesumar
Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

Detalhes do encontro
Aqui você encontra mais detalhes sobre local, horário e inscrição.

Formato
Qual seu nome?
Julio Vedovatto

Possui Twitter?, usaremos para divulgar
@vdvtt

Título da palestra
Exemplo de título

Descrição
Descrição da minha palestra

Votação
Para tornar a votação democrática as palestras aqui submetidas com mais 👍 serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by iamgbayer** [comment]
**Qual seu nome?**
Guilherme Bayer

**Possui Twitter?, usaremos para divulgar**
@guuibayer

**Título da palestra**
Controle de estado utilizando Redux

**Descrição**
Iremos entender o conceito por trás do nome Redux e o que ele busca resolver.

**Comment by luisberns** [comment]
Qual seu nome?
Luis Berns

Possui Twitter?, usaremos para divulgar
@louisuntitled

Título da palestra
Acessibilidade no produto e ferramentas para devs

Descrição
Vou apresentar algumas preocupações sobre acessibilidade no desenvolvimento de produtos e interfaces, e mostrar algumas ferramentas de acessibilidade utilizadas no desenvolvimento. E também vai rolar uma dinâmica de imersão com um caso de acessibilidade utilizando um aplicativo.

**Comment by juliovedovatto** [comment]
Call for Papers encerrado. Agradecemos a participação e votos nos temas propostos. Para mais detalhes, acompanhem o evento.
