### ISSUE TITLE
FEMUG-MGA #18 - Evoa Aceleradora

### ISSUE THREAD

**Issue by juliovedovatto** [femugmga/palestras#16]
FEMUG-MGA 18 - Evoa Aceleradora
Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

Detalhes do encontro
Aqui você encontra mais detalhes sobre local, horário e inscrição.

Formato

**Qual seu nome?**
Julio Vedovatto

**Possui Twitter?, usaremos para divulgar**
@vdvtt

**Título da palestra**
Exemplo de título

**Descrição**
Descrição da minha palestra

**Votação**
Para tornar a votação democrática as palestras aqui submetidas com mais 👍 serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by juliovedovatto** [comment]
**Qual seu nome?**
Julio Vedovatto

**Possui Twitter?**
@vdvtt

**Título da palestra**
Como reduzir o impacto do JavaScript no tempo de carregamento da sua página

**Descrição**
Palestra abordando técnicas para conseguir reduzir o impacto do JavaScript no tempo de carregamento da página. Quando falamos em milhões (ou até bilhões) de pageviews, toda otimização é importante para um ótimo rank da página e redução da taxa de rejeição do usuário.

**Comment by frontendwizard** [comment]
**Qual seu nome?**
Juliano Rafael

**Possui Twitter?**
[frontendwizard](https://twitter.com/frontendwizard)

**Título da palestra**
A importância de UI/UX na popularização de cripto moedas

**Descrição**
Vamos bater um papo sobre quão importante é abstrair a complexidade na UI para aumentar o engajamento dos usuários e popularizar as cripto moedas e porque há um espaço grande de oportunidades para aplicações nessa área.

**Comment by juliovedovatto** [comment]
Call for Papers encerrado. Agradecemos a participação e votos nos temas propostos. Para mais detalhes, acompanhem o evento.
