### ISSUE TITLE
FEMUG -MGA #19 - Tecnospeed

### ISSUE THREAD

**Issue by juliovedovatto** [femugmga/palestras#17]
FEMUG-MGA 19 - Tecnospeed
Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

Detalhes do encontro
Aqui você encontra mais detalhes sobre local, horário e inscrição.

Formato

**Qual seu nome?**
Julio Vedovatto

**Possui Twitter?, usaremos para divulgar**
@vdvtt

**Título da palestra**
Exemplo de título

**Descrição**
Descrição da minha palestra

**Votação**
Para tornar a votação democrática as palestras aqui submetidas com mais 👍 serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by JFTavares** [comment]
FEMUG-MGA 19 - Tecnospeed - Proposta TALK


Qual seu nome?
José Fernando Tavares

Possui Twitter?, usaremos para divulgar
@JFTavares

Título da palestra
Acessibilidade: desafio e oportunidade

Descrição
Um bate-papo sobre a acessibilidade e a sua importância em um bom projeto de UX e sua função social no atual cenário brasileiro. Como implementá-la nos nossos projetos e criar sites, aplicações e publicações digitais que sejam realmente acessíveis? Quais as oportunidades que um frontend acessível pode oferecer? Quais os desafios para um design inclusivo? Os novos recursos promovidos pelo W3C para a acessibilidade em publicações digitais.

**Comment by andrevandal** [comment]
**Qual seu nome?**
André Van Dal

**Possui Twitter?, usaremos para divulgar**
@derevandal
 
**Título da palestra**
Images Responsivas: Milagre ou Gambiarra?

**Descrição**
Layout responsivo é mais que um requisito do front-end que se preze. Contudo, o que fazer para entregar uma imagem para tantos tipos de telas com tamanho e densidade de pixeis distintos? Falarei sobre o elemento `picture`, tipos de imagem (jpg, png, svg e webp), media queries, densidade de pixeis e mostrarei um serviço (com free tier excelente) que ajudará a resolver isso junto com um componente em Vue.js.

**Comment by FactorySolution** [comment]
Qual seu nome?
André Luiz de Oliveira

Possui Twitter?, usaremos para divulgar
@FactorySolution

Título da palestra
Docker com Spring Boot e Angular

Descrição
Docker é muito bacana não? E se eu lhe apresentar como podemos deixar nossas aplicações feitas com Spring rodando em um ambiente docker sem complicação, utilizando um banco de dados mysql e de quebra um front-end em angular, tudo no mesmo contexto. :D

**Comment by leonardoelias** [comment]
**Qual seu nome?**
Leonardo Elias

**Possui Twitter?**
@leonardoelias_

**Título da palestra**
Design systems  -  O que é, desafios, ferramentas e como podemos construir.

**Descrição**
Onde quer que você olhe, as empresas estão lançando novos Design systems como como Polaris, Lightning ou Carbon e outros como Material UI sendo usado em todos os outros projetos por causa de sua alta qualidade e acessibilidade.

“Os sistemas de projeto fornecem um mapa conveniente, centralizado e em evolução dos territórios de produtos conhecidos da marca com indicadores direcionais para ajudá-lo a explorar novas regiões.” –Chris Messina, evangelista técnico e ex-líder de experiência de desenvolvimento na Uber

**Comment by FactorySolution** [comment]
**Qual seu nome?**
André Luiz de Oliveira

**Possui Twitter?, usaremos para divulgar**
@FactorySolution

**Título da palestra**
Utilizando Thymeleaf como template engine em aplicações Spring

**Descrição**
Você gosta de trabalhar com Spring? Qual framework para o front-end você utiliza?
Irei apresentar a vocês como podemos utilizar a engine Thymeleaf em nossos projetos Spring.
Pensa numa engine bacana, leve, não é intrusiva no seu código, ela é linda 💃 .

**Comment by joaocunha** [comment]
*Qual seu nome?*
João Cunha

*Possui Twitter?, usaremos para divulgar*
@joaocunha

*Título da palestra*
Além dos milissegundos: a Psicologia da Performance

*Descrição*
A noção de tempo pode ser dividida em duas formas: objetiva e subjetiva. Enquanto a noção objetiva é facilmente mensurável, a subjetiva envolve a percepção psicológica de como o tempo transcorre.

Estas noções também se aplicam à Web; compressão de imagens, caching e redução de requisições HTTP são exemplos de técnicas consagradas que impactam a performance de forma mensurável. 

No entanto, os números absolutos não contam a história completa - a performance está diretamente ligada à maneira como nossos cérebros percebem o carregamento da página. APIs lentas, redirecionamentos e requisições assíncronas são alguns dos gargalos de performance negligenciados por fugirem ao nosso controle.

Nessa palestra vou explicar como nossos cérebros entendem o tempo e falar de conceitos para aumentar a percepção de performance com técnicas que apliquei com sucesso em produtos que somam bilhões de page views mensais.

**Comment by juliovedovatto** [comment]
Call for Papers encerrado. Agradecemos a participação e votos nos temas propostos. Para mais detalhes, acompanhem o evento.

**Comment by juliovedovatto** [comment]
Call for Papers encerrado. Agradecemos a participação e votos nos temas propostos. Para mais detalhes, acompanhem o evento.
