### ISSUE TITLE
FEMUG -MGA #20 - Especial Mesa de Bar

### ISSUE THREAD

**Issue by juliovedovatto** [femugmga/palestras#19]
FEMUG-MGA 20 - Especial Mesa de Bar no Sumério
Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

Detalhes do encontro
Aqui você encontra mais detalhes sobre local, horário e inscrição.

Formato

**Qual seu nome?**
Julio Vedovatto

**Possui Twitter?, usaremos para divulgar**
@vdvtt

**Título da palestra**
Exemplo de título

**Descrição**
Descrição da minha palestra

**Votação**
Para tornar a votação democrática as palestras aqui submetidas com mais 👍 serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by uselessdev** [comment]
**Qual seu nome?**
Wallace

**Possui Twitter?, usaremos para divulgar**
@uselessdevelop

**Título da palestra**
React e Firebase: Porque e como

**Descrição**
Firebase é sem dúvida uma das melhores ferramentas para prototipação de aplicações, mas é possível ir mais além e criar soluções completas desde gerenciamento de usuários até deploy de uma aplicação web.

**Comment by frontendwizard** [comment]
**Qual seu nome?**
Juliano Rafael

**Twitter**
[@frontendwizard](https://twitter.com/frontendwizard)

**Título da palestra**
Meu Website é Mais Rápido que o Seu

**Descrição**
A web hoje exige um padrão de desempenho alto e requer dezenas de micro ajustes para que seu site seja rápido. E se não precisássemos nos preocupar com desempenho, só focar no conteúdo e ainda assim desenvolver um PWA com score 100 no audits? GatsbyJS é um framework para PWAs aonde desempenho máximo é default. Vamos discutir um pouco sobre como é a experiência do desenvolvedor ao desenvolver um site/app com GatsbyJS.

**Comment by juliovedovatto** [comment]
FEMUG-MGA 19 - Especial Mesa de Bar no Sumério
Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

Detalhes do encontro
Aqui você encontra mais detalhes sobre local, horário e inscrição.

Formato

**Qual seu nome?**
Julio Vedovatto

**Possui Twitter?, usaremos para divulgar**
@vdvtt

**Título da palestra**
O que faz alguém um bom desenvolvedor frontend?

**Descrição**
Talk voltada mais para profissão, com apresentação de tópicos que considero fundamental para ser um bom desenvolvedor de frontend nestes tempos atuais. É um assunto subjetivo, porém é um compartilhamento de opinião para ajudar a formar pensamento crítico a respeito.

**Votação**
Para tornar a votação democrática as palestras aqui submetidas com mais 👍 serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.
