### ISSUE TITLE
FEMUG-MGA #4 - SERRABITS

### ISSUE THREAD

**Issue by juliovedovatto** [femugmga/palestras#2]
# FEMUG-MGA #4 - SERRABITS 

Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

## Detalhes do encontro
[Aqui](http://meetu.ps/36BhQq) você encontra mais detalhes sobre local, horário e outras informações.

## Formato
**Qual seu nome?** 
Julio Vedovatto

**Possui Twitter?, usaremos para divulgar**
vdvtt

**Título da palestra**
Otimizações CSS - utilizando tasks

**Descrição**
Abordagem de como pode-se aumentar a eficiência no desenvolvimento CSS utilizando ferramentas automatizadoras de tarefas, como ```grunt```, ```gulp``` e ```npm```

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1: serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by iamgbayer** [comment]
**Qual seu nome?**
Guilherme Bayer

**Possui Twitter?, usaremos para divulgar**
guuibayer

**Título da palestra**
Do callback hell a async functions

**Descrição**
Que tal conhecer mais sobre as features para se trabalhar com código assíncrono no javascript?

**Comment by rhnonose** [comment]
**Qual seu nome?**
Rodrigo Nonose

**Possui Twitter?, usaremos para divulgar**
RodrigoNonose

**Título da palestra**
Introdução a Elm: programação funcional no front-end

**Descrição**
Elm é uma linguagem de programação estaticamente tipada e puramente funcional que compila pra javascript. Possui ênfase em usabilidade, performance e robustez e influencia várias funcionalidades de frameworks front-end.

**Comment by ferfabricio** [comment]
**Qual seu nome?**
Fernando Fabricio dos Santos

**Possui Twitter?, usaremos para divulgar**
ferfabricio

**Título da palestra**
Criando um App de cardápio com Ember.js

**Descrição**
Segundo o radar da ThoughtWorks o Ember.js é uma dos frameworks que devem ser adotados. Nessa talk vamos fazer um live code para montar um pequeno app de cardápio utilizando o Ember.js, mostrando alguns detalhes e como iniciar um projeto neste framework.
