### ISSUE TITLE
FEMUG -MGA #21 - Elotech

### ISSUE THREAD

**Issue by juliovedovatto** [femugmga/palestras#20]
FEMUG-MGA 21 - Elotech
Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

Detalhes do encontro
Aqui você encontra mais detalhes sobre local, horário e inscrição.

Formato

**Qual seu nome?**
Julio Vedovatto

**Possui Twitter?, usaremos para divulgar**
@vdvtt

**Título da palestra**
Exemplo de título

**Descrição**
Descrição da minha palestra

**Votação**
Para tornar a votação democrática as palestras aqui submetidas com mais 👍 serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by wwwflorencio** [comment]
**Nome**
Marcos Florencio

**Twitter**
[@eptaccio](http://twitter.com/eptaccio)

**Título da palestra**
Undux, uma alternativa **simples pacas** ao Redux

**Descrição**
Apresentação do Undux, uma boa alternativa para gerenciamento de estado em aplicações React, com suporte a hooks.

**Comment by gustavoquinalha** [comment]
**Nome**
Gustavo Quinalha

**Twitter**
@gustavoquinalha

**Título da palestra**
Design Systems

**Descrição**
Vou falar um pouco sobre a construção de um Design Systems desde as etapas de inventário até o desenvolvimento, contando um pouco sobre a minha experiência e desafios desenvolvendo um.

**Comment by rhnonose** [comment]
#### Nome
Rodrigo Nonose

#### Twitter
@backendwizard

#### Título da Palestra
Frontend sem Javascript com Phoenix LiveView

#### Descrição
Apresentar-lhes-ei o Phoenix LiveView, a lib que te promete renderização dinâmica no frontend sem javascript.

**Comment by dotenorio** [comment]
**Qual seu nome?**
Fernando M Tenório

**Possui Twitter?, usaremos para divulgar**
@dotenorio

**Título da palestra**
Por que diabos as pessoas estão escrevendo CSS usando JS?

**Descrição**
Tudo indica que existe um futuro para o CSS, escreve-lo em JS e assim torna-lo (em teoria) mais poderoso e manutenível. Mas será que isso é realmente bom? Os pre-processadores de CSS não resolvem isso?
Descubra, no próximo episódio..

**Comment by juliovedovatto** [comment]
Call for Papers encerrado. Agradecemos a participação e votos nos temas propostos. Para mais detalhes, acompanhem o evento.
