### ISSUE TITLE
FEMUG-MGA #22 - EVOA

### ISSUE THREAD

**Issue by juliovedovatto** [femugmga/palestras#21]
FEMUG-MGA 22 - EVOA
Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

Meetup http://bit.ly/femugmga22 

Detalhes do encontro
Aqui você encontra mais detalhes sobre local, horário e inscrição.

Formato

**Qual seu nome?**
Julio Vedovatto

**Possui Twitter?, usaremos para divulgar**
@vdvtt

**Título da palestra**
Exemplo de título

**Descrição**
Descrição da minha palestra

**Votação**
Para tornar a votação democrática as palestras aqui submetidas com mais 👍 serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by JFTavares** [comment]
**Qual seu nome?**
José Fernando Tavares

**Possui Twitter?, usaremos para divulgar**
@JFTavares

**Título da palestra**
Acessibilidade: desafio e oportunidade

**Descrição**
Um bate-papo sobre a acessibilidade e a sua importância em um bom projeto. Sua função social no atual cenário brasileiro. O que diz a lei Brasileira de Inclusão e o que dizem as documentações do W3C sobre o tema. Quais as oportunidades que um frontend acessível pode oferecer? Quais os desafios para um design inclusivo? Como implementá-la nos nossos projetos e criar sites, aplicações e publicações digitais que sejam realmente acessíveis? Como testar as características de acessibilidade. Os novos recursos promovidos pelo W3C para a acessibilidade em publicações digitais.

**Comment by rhnonose** [comment]
**Nome**
Rodrigo Nonose

**Twitter**
`@backendwizard`

**Título**
Phoenix LiveView: a web sem javascript

**Descrição**
Se você é como eu, cansado de javascript, procurando alternativas, tentando lidar com `undefined is not a function` e não consegue mais aturar, os seus problemas acabaram! A solução acaba de ser lançada e essa palestra vai apresentar ela pra você.

Phoenix é um framework web em Elixir, uma linguagem de programação funcional que compila pra máquina virtual Erlang. Usando sua alta disponibilidade na capacidade máxima, LiveView possibilidade renderização dinâmica no servidor não só possível mas com performance comparável.

Com comunicação (preferencialmente) websocket, o client manda ao servidor o que precisa ser renderizado e substitui no frontend quando temrina. Essa solução praticamente remove a necessidade de ter javascript renderizando no frontend, solução perfeita a javascript haters como eu.

**Comment by juliovedovatto** [comment]
Call for Papers encerrado. Agradecemos a participação e votos nos temas propostos. Para mais detalhes, acompanhem o evento.
