### ISSUE TITLE
FEMUG #24 - Tecnospeed

### ISSUE THREAD

**Issue by juliovedovatto** [femugmga/palestras#23]
FEMUG-MGA 24 - Tecnospeed
Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

Detalhes do evento (Meetup) http://bit.ly/femugmga24

Detalhes do encontro
Aqui você encontra mais detalhes sobre local, horário e inscrição.

Formato

**Qual seu nome?**
Julio Vedovatto

**Possui Twitter?, usaremos para divulgar**
@vdvtt

**Título da palestra**
Exemplo de título

**Descrição**
Descrição da minha palestra

**Votação**
Para tornar a votação democrática as palestras aqui submetidas com mais 👍 serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by andrevandal** [comment]
**Qual seu nome?**
André Van Dal

**Possui Twitter?, usaremos para divulgar**
@derevandal

**Título da palestra**
Gridsome + Netlify CMS

**Descrição**
Já pensou em usar um CMS git-based sem precisar se preocupar com manter ele online e sem se preocupar com um banco de dados? Se você já usa arquivos .yml, .md ou .json para compor seu site de forma estática, você poderá começar a editar esses dados através de uma plataforma visual agradável que fará commits dentro do seu repositório.
Somado a isso, mostrarei o Gridsome... Um gerador de sites estáticos para Vue com GraphQl.

**Comment by willian-coelho-da-cunha** [comment]
**Qual é o seu nome?**
Willian Coelho da Cunha

**Possui Twitter? Usaremos para divulgar.**
@willianewcunha

**Título da palestra**
Componentes dinâmicos em Angular

**Descrição**
Angular é um dos frameworks que utiliza o conceito de web component. Com limite, estratégia e trabalho em equipe é possível alcançar resultados satisfatórios em diversos critérios: manutenção da aplicação ou parte dela, reusabilidade do código, etc.
A intenção é a de percorrer alguns conceitos relativos ao Angular, bem como o conceito em evidência: componentes dinâmicos, sua implementação e algumas de suas aplicações.

**Comment by juliovedovatto** [comment]
Call for Papers encerrado. Agradecemos a participação e votos nos temas propostos. Para mais detalhes, acompanhem o evento.
