### ISSUE TITLE
FEMUG-MGA #25 - CRMALL

### ISSUE THREAD

**Issue by juliovedovatto** [femugmga/palestras#24]
FEMUG-MGA 25 - CRMALL
Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

Detalhes do evento (Meetup) http://bit.ly/femugmga25

Detalhes do encontro
Aqui você encontra mais detalhes sobre local, horário e inscrição.

Formato

**Qual seu nome?**
Julio Vedovatto

**Possui Twitter?, usaremos para divulgar**
@vdvtt

**Título da palestra**
Exemplo de título

**Descrição**
Descrição da minha palestra

**Votação**
Para tornar a votação democrática as palestras aqui submetidas com mais 👍 serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by dotenorio** [comment]
**Qual seu nome?**
Fernando Migliorini Tenório

**Possui Twitter?**
[@dotenorio](https://twitter.com/dotenorio)

**Título da palestra**
Qual será o futuro do CSS?

**Descrição**
Vivemos um momento em que o frontend de maneira geral está evoluindo muito, estamos ganhando ferramentas, libs, frameworks que tornam essa área mais exigente e robusta. Porém, onde o CSS está nessa evolução? A minha proposta é reunir artigos, vídeos e experiências sobre o futuro do CSS e traze-los em uma talk afim de esclarecer (ou não) qual o futuro do CSS...

**Comment by leonardoelias** [comment]
Qual seu nome?
Leonardo Elias

Possui Twitter?, usaremos para divulgar
@leonardoelias_

Título da palestra
Front-end Ops

Descrição
O Front-End Ops é uma combinação de práticas e ferramentas que torna a entrega de aplicativos Web mais eficiente no modern fron-tend. Qual o motivo pelo, qual os compiladores parecem ser a nova geração de estruturas de front-end. Quais são as armadilhas comuns na construção e manutenção de aplicativos da Web e qual conjunto de práticas que as equipes podem adotar para fornecer a melhor experiência ao usuário, mantendo a maior parte de sua autonomia. Todos os itens acima para chegar a uma conclusão: as equipes precisam de uma cultura Front-End Ops para ter sucesso na era dos Microfrontends.

**Comment by juliovedovatto** [comment]
Call for Papers encerrado. Agradecemos a participação e votos nos temas propostos. Para mais detalhes, acompanhem o evento.
