### ISSUE TITLE
FEMUG-MGA #26 - PUCPR

### ISSUE THREAD

**Issue by juliovedovatto** [femugmga/palestras#25]
FEMUG-MGA 25 - PUCPR
Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

Detalhes do evento (Meetup) http://bit.ly/femugmga26

Detalhes do encontro
Aqui você encontra mais detalhes sobre local, horário e inscrição.

Formato

**Qual seu nome?**
Julio Vedovatto

**Possui Twitter?, usaremos para divulgar**
@vdvtt

**Título da palestra**
Exemplo de título

**Descrição**
Descrição da minha palestra

**Votação**
Para tornar a votação democrática as palestras aqui submetidas com mais 👍 serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by leonardoelias** [comment]
Qual seu nome?
Leonardo Elias

Possui Twitter?
@leonardoelias

Título da palestra
Construindo arquitetura resilientes no frontend

Descrição
Mudança é inevitável. Então é legado. E com muita frequência, nós, como desenvolvedores (que adoram resolver problemas codificando), caímos na armadilha de acreditar que a única maneira de consertá-lo é reescrevendo tudo de novo e de novo. Mas como podemos projetar uma arquitetura de aplicativo que seja mais resiliente a mudanças? Nesta palestra, veremos técnicas específicas que você pode usar hoje para impedir que seu aplicativo se transforme naquela infame bola de lama.

**Comment by JFTavares** [comment]
Qual seu nome?
José Fernando Tavares

Possui Twitter?, usaremos para divulgar
@JFTavares

Título da palestra
As diretrizes WCAG para acessibilidade na prática

Descrição
Todos já sabemos que acessibilidade é fundamental. Mas como aplicar na prática a WCAG? A ideia da talk é trazer algumas indicações práticas de como melhorar a acessibilidade das nossas interfaces. Vamos dar uma olhada no HTML semântico, em aspectos de acessibilidade do CSS, e em alguns frameworks.

**Comment by iamgbayer** [comment]
**Qual seu nome?**
Guilherme Bayer

**Possui Twitter?**
@iamgbayer

**Título da palestra**
Introdução a Micro Frontends

**Descrição**
Iremos conversar um pouco sobre esse modelo arquitetural que vem se tornando mais discutido devido a complexidade que o ecossistema frontend vem tendo.

**Comment by juliovedovatto** [comment]
Call for Papers encerrado. Agradecemos a participação e votos nos temas propostos. Para mais detalhes, acompanhem o evento.
