### ISSUE TITLE
FEMUG-MGA #5 - UOL BoaCompra

### ISSUE THREAD

**Issue by iamgbayer** [femugmga/palestras#3]
# FEMUG-MGA #5 - UOL BoaCompra
Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

## Detalhes do encontro
[Aqui](http://meetu.ps/39YHD5) você encontra mais detalhes sobre local, horário e inscrição.

## Formato
**Qual seu nome?** 
Guilherme Bayer

**Possui Twitter?, usaremos para divulgar**
guuibayer

**Título da palestra**
Exemplo de título

**Descrição**
Descrição da minha palestra

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1: serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by geovanisouza92** [comment]
#### Qual seu nome?
Geovani de Souza

#### Possui Twitter?, usaremos para divulgar
geovanisouza92

#### Título da palestra
Web Infinita com Serverless

#### Descrição
Como utilizar Serverless para entregar o front-end e uma API completa com o mínimo de esforço e máxima escalabilidade.

**Comment by rhnonose** [comment]
**Qual seu nome?**
Rodrigo Nonose

**Possui Twitter?, usaremos para divulgar**
RodrigoNonose

**Título da palestra**
Introdução a Elm: programação funcional no front-end

**Descrição**
Elm é uma linguagem de programação estaticamente tipada e puramente funcional que compila pra javascript. Possui ênfase em usabilidade, performance e robustez e influencia várias funcionalidades de frameworks front-end.

**Comment by gustavoquinalha** [comment]
Qual seu nome?
Gustavo Quinalha

Possui Twitter?, usaremos para divulgar
@gustavoquinalha

Título da palestra
Flexbox do jeito certo!

Descrição
Abordarei todos os elementos do flexbox e sua correta utilização, monstrando dicas e exemplos.
