### ISSUE TITLE
FEMUG-MGA #6 - FCV

### ISSUE THREAD

**Issue by iamgbayer** [femugmga/palestras#4]
# FEMUG-MGA #6 - FCV
Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

## Detalhes do encontro
[Aqui](http://meetu.ps/3c4j0K) você encontra mais detalhes sobre local, horário e inscrição.

## Formato
**Qual seu nome?** 
Guilherme Bayer

**Possui Twitter?, usaremos para divulgar**
guuibayer

**Título da palestra**
Exemplo de título

**Descrição**
Descrição da minha palestra

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1: serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by rhnonose** [comment]
### Qual seu nome?
Rodrigo Nonose
### Possui Twitter?
RodrigoNonose
### Título da palestra
Live coding em Elm
### Descrição
Farei um live coding in Elm para demonstrar como utilizar os elementos básicos da linguagem

**Comment by juliovedovatto** [comment]
### Qual seu nome?
Julio Vedovatto

### Possui Twitter?
vdvtt

### Título da palestra
Você não precisa tanto do jQuery: usando vanilla JS e CSS 

### Descrição
jQuery and e seus parecidos são ótimos e os usando, se torna mais fácil desenvolver sua aplicação web. Se você está desenvolvendo algo, tenha em mente que dependendo do caso, não precisará usar o jQuery. A talk mostrará exemplos que com linhas puras (vanilla code) de Javascript você poderá ter o mesmo resultado, assim como usar animações CSS para problemas de animação.

**Comment by hiwllc** [comment]
### Qual seu nome?
Wallace Batista

### Possui Twitter?
uselessdevelop

### Título da palestra
Stateful & Stateless components

### Descrição
Vamos falar um pouco sobre as principais diferenças entre Componentes Stateful e Stateless e quando usar um ou outro.

**Comment by gustavoquinalha** [comment]
**Qual seu nome?**
Gustavo Quinalha

**Possui Twitter?**
gustavoquinalha

**Título da palestra**
Criando um mini framework com flexbox.

**Descrição**
Criaremos um grid e algumas classes necessárias para criar qualquer layout básico ou avançado, e  entäo criaremos uma estrutura e alguns componentes.

**Comment by iamgbayer** [comment]
[Aqui](http://meetu.ps/3c4j0K) pode ser encontrado mais detalhes do encontro, valeu galera!
