### ISSUE TITLE
FEMUG-MGA #7 - Saura Consultoria

### ISSUE THREAD

**Issue by iamgbayer** [femugmga/palestras#5]
# FEMUG-MGA #7 - Saura Consultoria
Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

## Detalhes do encontro
[Aqui](http://meetu.ps/3cKt8g) você encontra mais detalhes sobre local, horário e inscrição.

## Formato
**Qual seu nome?** 
Guilherme Bayer

**Possui Twitter?, usaremos para divulgar**
guuibayer

**Título da palestra**
Exemplo de título

**Descrição**
Descrição da minha palestra

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1: serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by geovanisouza92** [comment]
Qual seu nome?
Geovani de Souza

Possui Twitter?, usaremos para divulgar
geovanisouza92

Título da palestra
Webpack: O que ele pode fazer por você?

Descrição
Entendendo pra que serve e quais as vantagens de usar webpack para empacotar sua aplicação.

**Comment by gustavoquinalha** [comment]
**Qual seu nome?**
Gustavo Quinalha

**Possui Twitter?, usaremos para divulgar**
@gustavoquinalha

**Título da palestra**
Um mundo de possibilidades com flexbox.

**Descrição**
Vamos ver e fazer alguns exemplos para entender aonde usar flexbox, também vou dar início no conteúdo de CSS Grid Layout.

**Comment by lucassmacedo** [comment]
Qual seu nome?
**Lucas Macedo**

Possui Twitter?, usaremos para divulgar
**luuckymacedo**

Título da palestra
**Introdução ao VuejS2**

Descrição
**Apresentação dos conceitos básicos do VueJS**

**Comment by hiwllc** [comment]
**Qual seu nome?**
Wallace Batista

**Possui Twitter?, usaremos para divulgar**
uselessdevelop

**Título da palestra**
Componentes reutilizaveis com React

**Descrição**
Reutilizando componentes entre aplicações com React e Storybook

**Comment by iamgbayer** [comment]
**Qual seu nome?**
Guilherme Bayer

**Possui Twitter?, usaremos para divulgar**
guuibayer

**Título da palestra**
Um pouco mais sobre web offline e service workers

**Descrição**
Iremos ver um pouco sobre alguns recursos que estão disponíveis com a utilização de Service Workers sendo alguns para uma melhor experiência do usuário no cenário offline.

**Comment by iamgbayer** [comment]
Obrigado pelas propostas pessoal, mais detalhes [aqui](http://meetu.ps/3cKt8g), esse encontro terá as 3 talks mais curtidas pela galera, fica o convite para o próximo encontro!
