### ISSUE TITLE
# FEMUG-MGA #8 - Tecnospeed

### ISSUE THREAD

**Issue by iamgbayer** [femugmga/palestras#6]
# FEMUG-MGA #8 - Tecnospeed
Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

## Detalhes do encontro
[Aqui](http://meetu.ps/c/2Vh9G/plKvx/f) você encontra mais detalhes sobre local, horário e inscrição.

## Formato
**Qual seu nome?** 
Guilherme Bayer

**Possui Twitter?, usaremos para divulgar**
guuibayer

**Título da palestra**
Exemplo de título

**Descrição**
Descrição da minha palestra

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1: serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by gustavoquinalha** [comment]
**Qual seu nome?**
Gustavo Quinalha

**Possui Twitter?, usaremos para divulgar**
**github**.com/gustavoquinalha

**Título da palestra**
Pure CSS Animations

**Descrição**
Abordarei sobre Animações com CSS puro, o que podemos fazer, aonde podemos usar, quando usar determinadas propriedades com vários exemplos.

**Comment by uselessdev** [comment]
**Qual seu nome?**
Wallace Batista

**Possui Twitter?, usaremos para divulgar**
uselessdevelop

**Título da palestra**
CSS: Custom properties

**Descrição**
CSS Custom Properties ou váriaveis no css podem ajudar bastante na hora de criar temas e customizar pequenos componentes do seu template.

**Comment by guuibayer** [comment]
**Qual seu nome?**
Guilherme Bayer

**Possui Twitter?, usaremos para divulgar**
guuibayer

**Título da palestra**
Um pouco mais sobre web offline e service workers

**Descrição**
Iremos ver um pouco sobre alguns recursos que estão disponíveis com a utilização de Service Workers sendo alguns para uma melhor experiência do usuário no cenário offline.

**Comment by luisberns** [comment]
**Qual seu nome?**
Luís Guilherme

**Possui Twitter?, usaremos para divulgar**
louisuntitled

**Título da palestra**
Incluindo UX a partir do Gerenciamento do Produto

**Descrição**
Irei apresentar um projeto em desenvolvimento, no qual estamos otimizando o Gerenciamento de Produto para trabalhar com UX do Produto como um todo, com objetivo de conseguirmos melhores resultados de UX.

**Comment by hygorzorak** [comment]
**Qual seu nome?**
Hygor Zorak

**Possui Twitter?**
hygorzorak

**Título da palestra**
Introdução sobre GraphQL

**Descrição**
Apresentar a origem e os conceitos iniciais do que seja o GraphQL, debatendo sobre vantagens e desvantagens da tecnologia

**Comment by iamgbayer** [comment]
Obrigado a todos pelas propostas, você pode conferir mais detalhes do encontro por [aqui](http://meetu.ps/c/2Vh9G/plKvx/f).
