### ISSUE TITLE
# FEMUG-MGA #9 - Matera

### ISSUE THREAD

**Issue by iamgbayer** [femugmga/palestras#7]
# FEMUG-MGA #9 - Matera
Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

## Detalhes do encontro
[Aqui](https://goo.gl/2wroFx) você encontra mais detalhes sobre local, horário e inscrição.

## Formato
**Qual seu nome?** 
Guilherme Bayer

**Possui Twitter?, usaremos para divulgar**
guuibayer

**Título da palestra**
Exemplo de título

**Descrição**
Descrição da minha palestra

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1: serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by leandronishijima** [comment]
**Qual seu nome?**
Leandro Nishijima

**Possui Twitter?**
leandronishijim

**Título da palestra**
Iniciando com testes em NodeJS!

**Descrição**
Apresentarei uma introdução às ferramentas mocha, Chai.js e sinon.js e como utiliza-las para criar testes automatizados em um projeto com NodeJS.

**Comment by lucassmacedo** [comment]
**Qual seu nome?**
Lucas Macedo

**Possui Twitter?**
luuckymacedo

**Título da palestra**
Nuxt.JS - Desenvolvendo Aplicações SSR com Vue

**Descrição**
Introdução aos conceitos básico do NuxtJS e como criar aplicações SSR usando micro-framework feito em Vue.

**Comment by CleberDSantos** [comment]
**Qual seu nome?**
José Cléber

**Possui Twitter?**
@cleberdsantos

**Título da palestra**
Typescript em BI? Sim e funciona lindamente!

**Descrição**
Nesta apresentação irei compartilhar como funciona o desenvolvimento de extensões para Ferramentas de BI, tais como Qlikview e Microsoft Power BI utilizando Typescript. Iremos criar uma extensão Power BI do zero utilizando VS Code. Esse conhecimento é fruto do trabalho de um ano e meio que atualmente exerço remotamente em uma empresa localizada em Dallas - TX - EUA.

**Comment by luisberns** [comment]
**Qual seu nome?**
Luís Guilherme

**Possui Twitter?**
@louisuntitled

**Título da palestra**
UX na Prática, como utilizar os entregáveis no produto

**Descrição**
Irei apresentar algumas vertentes definidas pelo mercado de UX (Designer, Researcher, Strategist, Engineer) e como UX é desenvolvido e aplicado no produto. Veremos alguns cases de aplicação de melhorias, de visual até performance!

**Comment by juliovedovatto** [comment]
Obrigado a todos pelas propostas. Mais detalhes do evento podem ser acompanhador por [aqui](https://www.meetup.com/pt-BR/femugmga/events/245190524/)
