### ISSUE TITLE
# FEMUG-MGA #10 - Edição especial no Porão Bar

### ISSUE THREAD

**Issue by iamgbayer** [femugmga/palestras#8]
# FEMUG-MGA #10 - Edição especial no Porão Bar
Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

## Detalhes do encontro
Pessoal, como uma pequena comemoração à nossa 10ª edição, iremos realizá-la no Porão Bar, então convide os amigos e vamos participar de uma edição especial com muito conhecimento e networking!

**Essa edição contará com duas talks, fique a vontade para submeter e agregar conhecimento a galera!**

[Aqui](https://goo.gl/qAcuxK) você encontra mais detalhes sobre local, horário e inscrição.

## Formato
**Qual seu nome?** 
Guilherme Bayer

**Possui Twitter?, usaremos para divulgar**
guuibayer

**Título da palestra**
Exemplo de título

**Descrição**
Descrição da minha palestra

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1: serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by gustavoquinalha** [comment]
**Qual seu nome?**
Gustavo Quinalha

**Possui Twitter?, usaremos para divulgar**
@gustavoquinalha

**Título da palestra**
CSS Patterns

**Descrição**
Iremos debater porque padrões são necessários, tanto código quanto visualmente. Vou mostrar alguns exemplo e casos que dão medo.

**Comment by iamgbayer** [comment]
**Qual seu nome?**
Guilherme Bayer

**Possui Twitter?, usaremos para divulgar**
guuibayer

**Título da palestra**
Um pouco mais sobre Web Offline e Service Workers

**Descrição**
Veremos um pouco sobre alguns recursos que estão disponíveis com a utilização de Service Workers, formas de armazenamento no client e como isso contribui para uma experiência do usuário nesse cenário.

**Comment by juliovedovatto** [comment]
Obrigado a todos pelas propostas. Mais detalhes do evento podem ser acompanhador por [aqui](https://www.meetup.com/pt-BR/femugmga/events/246918224/)
