### ISSUE TITLE
# FEMUG-MGA #11 - Tecnospeed

### ISSUE THREAD

**Issue by juliovedovatto** [femugmga/palestras#9]
# FEMUG-MGA 11 - Tecnospeed
Utilize o exemplo de formato abaixo para submeter sua palestra nessa issue.

## Detalhes do encontro
[Aqui](https://goo.gl/uWKePD) você encontra mais detalhes sobre local, horário e inscrição.

## Formato
**Qual seu nome?** 
Julio Vedovatto

**Possui Twitter?, usaremos para divulgar**
vdvtt

**Título da palestra**
Exemplo de título

**Descrição**
Descrição da minha palestra

## Votação
Para tornar a votação democrática as palestras aqui submetidas com mais :+1: serão escolhidas para o encontro, porém fica o convite para que você submeta também nos próximos encontros.

**Comment by frontendwizard** [comment]
Juliano Rafael
[@julianorsfarias](https://twitter.com/julianorsfarias)

**Estilizando componentes React com styled-components**

Uma talk sobre styled-components, uma lib de CSS-in-JS que vem ganhando bastante momento no ecosistema React.

**Comment by paulohenriqgoes** [comment]
Paulo Henrique Goes

**Chrome DevTools Essentials**

Uma talk sobre funcionalidades do  Chrome DevTools que podem ajudar na hora de prototipar ou depurar sua aplicação.

**Comment by leonardoelias** [comment]
Leonardo Elias dos Santos
_@leonardoelias__

**Bye bye foreach - map() filter() reduce()**

Você NÃO pode continuar programando sem aprender o quão poderoso são os métodos map, filter e reduce. Além de ser uma introdução ao paradigma funcional.

**Comment by juliovedovatto** [comment]
Obrigado a todos pelas propostas. Mais detalhes do evento podem ser acompanhador por [aqui](https://goo.gl/uWKePD)
